[build]
builder = "nixpacks"
buildCommand = """
apt-get update && apt-get install -y python3 python3-pip
pip3 install -r backend/requirements.txt
"""

[deploy]
startCommand = "python3 backend/src/bot/main.py"
restartPolicyType = "always" 