[build]
builder = "nixpacks"
buildCommand = """
apt-get update && apt-get install -y python3 python3-pip
cd backend && pip3 install -r requirements.txt
"""

[deploy]
startCommand = "cd backend && python3 src/bot/main.py"
restartPolicyType = "always" 